/**
 * git-agent.ts
 *
 * Handles all git operations after files are written:
 *  1. Checks committer identity against the allowlist
 *  2. Creates a feature branch (agent/feature-name-timestamp)
 *  3. Stages and commits the written files
 *  4. Pushes to remote
 *
 * Returns the branch name so github-agent.ts can create the PR.
 */

import { execSync } from 'child_process';
import { checkGitIdentity } from './permissions.config';
import { WrittenFile } from './file-writer';

export interface GitResult {
  success: boolean;
  branchName?: string;
  commitSha?: string;
  reason?: string;
}

function git(cmd: string, cwd: string): string {
  return execSync(`git ${cmd}`, { cwd, encoding: 'utf-8' }).trim();
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 50);
}

export async function runGitAgent(
  projectRoot: string,
  featureRequest: string,
  writtenFiles: WrittenFile[],
): Promise<GitResult> {
  console.log('\n📦 Git Agent — committing and pushing\n');

  if (writtenFiles.length === 0) {
    return { success: false, reason: 'No files were written — nothing to commit.' };
  }

  // ── Step 1: Permission check ───────────────────────────────────────────────
  let currentName = '', currentEmail = '';
  try {
    currentName  = git('config user.name', projectRoot);
    currentEmail = git('config user.email', projectRoot);
  } catch {
    return { success: false, reason: 'Could not read git user.name / user.email. Run: git config --global user.name "Your Name"' };
  }

  console.log(`  👤 Committer: ${currentName} <${currentEmail}>`);
  const permCheck = checkGitIdentity(currentName, currentEmail);
  if (!permCheck.allowed) {
    console.error(`  🚫 Permission denied: ${permCheck.reason}`);
    return { success: false, reason: permCheck.reason };
  }
  console.log('  ✅ Committer identity verified');

  // ── Step 2: Create feature branch ─────────────────────────────────────────
  const timestamp  = Date.now();
  const branchName = `agent/${slugify(featureRequest)}-${timestamp}`;

  try {
    git(`checkout -b ${branchName}`, projectRoot);
    console.log(`  🌿 Created branch: ${branchName}`);
  } catch (err: any) {
    return { success: false, reason: `Failed to create branch: ${err.message}` };
  }

  // ── Step 3: Stage written files ────────────────────────────────────────────
  for (const file of writtenFiles) {
    try {
      git(`add "${file.filePath}"`, projectRoot);
    } catch {
      // If path has issues, try adding all
      git('add -A', projectRoot);
      break;
    }
  }
  console.log(`  📂 Staged ${writtenFiles.length} file(s)`);

  // ── Step 4: Commit ─────────────────────────────────────────────────────────
  const commitMsg = [
    `feat: ${featureRequest}`,
    '',
    `Generated by Interview Simulator Agent Orchestrator`,
    `Files changed: ${writtenFiles.map(f => f.filePath).join(', ')}`,
    '',
    `Co-authored-by: Agent Orchestrator <agents@interview-simulator.ai>`,
  ].join('\n');

  try {
    git(`commit -m "${commitMsg.replace(/"/g, "'")}"`, projectRoot);
    const commitSha = git('rev-parse --short HEAD', projectRoot);
    console.log(`  💾 Committed: ${commitSha}`);

    // ── Step 5: Push to remote ───────────────────────────────────────────────
    git(`push -u origin ${branchName}`, projectRoot);
    console.log(`  🚀 Pushed branch: ${branchName}`);

    return { success: true, branchName, commitSha };
  } catch (err: any) {
    // Clean up: go back to main if push failed
    try { git('checkout main', projectRoot); } catch {}
    return { success: false, reason: `Git commit/push failed: ${err.message}` };
  }
}
